import p2 from './src/assets/p2.png'
import p6 from './src/assets/p6.png'
import p7 from './src/assets/p7.png'
import p8 from './src/assets/p8.png'
import p5 from './src/assets/p5.png'
import product1 from './src/assets/product1.jpg'
let data=[
    {
        id:"01",
        title:"cup",
        price:"50$",
        img:p2
    },
    {
        id:"02",
        title:"headphones",
        price:"30$",
        img:p6
    },
    {
        id:"03",
        title:"sets",
        price:"40$",
        img:p7
    },
    {
        id:"04",
        title:"cap",
        price:"20$",
        img:p8
    },
    {
        id:"05",
        title:"sungless",
        price:"100$",
        img:p5
    },
    {
        id:"06",
        title:"clock",
        price:"150$",
        img:product1
    },
    {
        id:"01",
        title:"cup",
        price:"50$",
        img:p2
    },
    {
        id:"02",
        title:"headphones",
        price:"30$",
        img:p6
    },
    {
        id:"03",
        title:"sets",
        price:"40$",
        img:p7
    },
    {
        id:"04",
        title:"cap",
        price:"20$",
        img:p8
    },
    {
        id:"05",
        title:"sungless",
        price:"100$",
        img:p5
    },
    {
        id:"06",
        title:"clock",
        price:"150$",
        img:product1
    },
    {
        id:"01",
        title:"cup",
        price:"50$",
        img:p2
    },
    {
        id:"02",
        title:"headphones",
        price:"30$",
        img:p6
    },
    {
        id:"03",
        title:"sets",
        price:"40$",
        img:p7
    },
    {
        id:"04",
        title:"cap",
        price:"20$",
        img:p8
    },
    {
        id:"05",
        title:"sungless",
        price:"100$",
        img:p5
    },
    {
        id:"06",
        title:"clock",
        price:"150$",
        img:product1
    }
]

export default data